spring:
  jackson:
    default-property-inclusion: non_null
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: dtorres
    password: dtorres
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  security:
    user:
      name: dtorres
      password: dtorres